### ISSUE TITLE
lualatex failing to find fonts or multiscript module

### ISSUE THREAD

**Issue by daniel-jakob** [xu-cheng/latex-action#111]
I've been trying to get my file to compile with lualatex, but some reason or another, I get strange errors which I've never seen before. Here is the log:

https://github.com/daniel-jakob/LaTeX-Compile-GitHub-Action-Test/actions/runs/3699073854/jobs/6266033706

There is a error on line 33 saying: No match for requested fontloader "fontloader-2022-10-03.lua".
and then also on 37 saying; Failed to load "luaotfload" module "multiscript".

I'm using the mathpazo and gillius fonts, but also setting some bold and italic fonts. See lines 146 to 152 in 
https://github.com/daniel-jakob/LaTeX-Compile-GitHub-Action-Test/blob/master/tex/lecturenotes.cls 
for exact commands used for fonts.

**Comment by xu-cheng** [comment]
This seems to be an issue of compiling particular LaTeX project instead of this action.  Please test your project locally including all the environment. 

I saw you set `TEXINPUTS` environment, which doesn't look right. Since it is an advance feature, I suggest to ask questions in stackexchange to figure out how to use it.
