### ISSUE TITLE
Use older TexLive distribution

### ISSUE THREAD

**Issue by flymg** [xu-cheng/latex-action#113]
How can i force the use of an older texlive distribution?

Background:
The current distribution (and the container) contains a major dependency issue causing this action to fail with:
>/opt/texlive/texdir/texmf-dist/tex/latex/amsmath/amsmath.sty:1560: LaTeX Error:
 Command \gather already defined.
               Or name \end... illegal, see p.192 of the manual.

https://github.com/latex-lineno/lineno/issues/5

**Comment by xu-cheng** [comment]
Due to the limitations of GitHub action, the only way to use the older docker image would be forking this action then changing the hardcoded image version. GitHub does not allow setting the base image as a runtime argument. 

This action’s docker image is automatically rebuilt every month. I can also trigger a manual new build when needed. So please let me know when this issue is fixed in upstream.

**Comment by flymg** [comment]
Is the Base Docker Image available somewhere?

**Comment by xu-cheng** [comment]
You can see all the history version of the image [here](https://github.com/xu-cheng/latex-docker/pkgs/container/texlive-full).

**Comment by aprokop** [comment]
Per [comment](https://github.com/latex-lineno/lineno/issues/5#issuecomment-1396590450), the `lineno` issue is fixed in `lineno` 5.1. It is available on [ctan](https://ctan.org/pkg/lineno?lang=en). I am not sure it will be picked up by a container rebuild, though.

**Comment by aprokop** [comment]
Can confirm correct build with the latest images (`20230201`).
