### ISSUE TITLE
Action fails due to TeXLive

### ISSUE THREAD

**Issue by LuckeeDev** [xu-cheng/latex-action#141]
I'm getting this error on the latest action runs:

```
Run pre compile commands

tlmgr: Local TeX Live (2023) is older than remote repository (2024).
Cross release updates are only supported with
  update-tlmgr-latest(.sh/.exe) --update
See https://tug.org/texlive/upgrade.html for details.
Error: Process completed with exit code 1.
```

It's weird because I didn't change any code in my [workflow file](https://github.com/LuckeeDev/LuTeX/blob/bff2713af69d7d9ea17a25871bf52a1509bf05ae/.github/workflows/publish.yml) and it worked perfectly until a few days ago. Is there any way to solve this?

**Comment by zydou** [comment]
Try to remove this line `pre_compile: tlmgr update --self && tlmgr update --all`

**Comment by LuckeeDev** [comment]
> Try to remove this line `pre_compile: tlmgr update --self && tlmgr update --all`

Yes I think that's the line that's causing the issue, but isn't it necessary for the action to work? How does it download dependencies otherwise?

**Comment by zydou** [comment]
Texlive use separate package repositories for different releases. Once a new release came out, the old package repository was frozen and moved to a separate location.

Since texlive 2024 was released on 2024-03-13, so the package repository for texlive 2023 moved to [historic archive](https://tug.org/historic/). To make the `tlmgr update` work on older release, you should change the repository localization by `tlmgr option repository https://ftp.math.utah.edu/pub/tex/historic/systems/texlive/2023/tlnet-final`

BTW, there is no need to run `tlmgr update --self && tlmgr update --all` on older releases since the historical repositories are frozen and no updates are available.

**Comment by xu-cheng** [comment]
Yes, the issue is due to the TeXLive 2024 release. And the tlmgr update is usually unnecessary as the base image is updated monthly.

Also FYI, the TeXLive 2024 will be available to this action on Apr 1.
