### ISSUE TITLE
Action suddenly stopped working

### ISSUE THREAD

**Issue by LuckeeDev** [xu-cheng/latex-action#142]
The action suddenly stopped working after a commit in which I changed almost nothing. Here are the two GitHub runs:
- [Working](https://github.com/LuckeeDev/LuTeX/actions/runs/8292749155/job/22694572404)
- [Not working](https://github.com/LuckeeDev/LuTeX/actions/runs/8333989225/job/22806617398)

This is my [workflow file](https://github.com/LuckeeDev/LuTeX/blob/main/.github/workflows/publish.yml). The issue seems to be coming from the `root.tex` file. Apparently, something broke with markdown inputs but I can't understand what it is.

**Comment by xu-cheng** [comment]
TeXLive 2024 is recently released. Your issue seems to come from it rather this action. Please refer to another resources such as Tex.stackexchange and Reddit to debug issues related to the TeXLive and latex usage in general. In the mean time, you can set the version to 2023 in this action. 

Also please include a [minimal working example](https://tex.meta.stackexchange.com/questions/228/ive-just-been-asked-to-write-a-minimal-working-example-mwe-what-is-that) to demonstrate your problem in the future.

**Comment by LuckeeDev** [comment]
Thank you! That worked.
