### ISSUE TITLE
Add back support for small texlive

### ISSUE THREAD

**Issue by PHPirates** [xu-cheng/latex-action#15]
As mentioned in #13, can you add back support for the small texlive image using texliveonfly? Having fast build times is definitely important for some people.

I'm not completely sure how that would be best set up, because these would be two separate docker images and I am not sure if you can switch Docker image from a github actions parameter.
Other possibility would be publishing a separate x.y.z-small version, or publishing a separate github action entirely. 
Neither of these sounds very easy to maintain to me, but maybe you have an idea.

What would help the build time even more, is if installed packages could be committed to the docker container and cached ([cache policy](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/caching-dependencies-to-speed-up-workflows#usage-limits-and-eviction-policy)), but I still need to try if this actually works.

Background: I want to point to your github action from https://github.com/PHPirates/travis-ci-latex-pdf and compare with other existing github actions for LaTeX.

**Comment by xu-cheng** [comment]
> I'm not completely sure how that would be best set up

I can add the support for small texlive back in the form of a new action. So it would look like this:
```yaml
- name: Compile LaTeX document
  uses: xu-cheng/latex-action/small@master
    with:
      root_file: main.tex
```

The issue I say is that this may not help to reduce the build time. Although, it would take less time to download the docker image, it could take even more times to install the package on the fly. You can actually test this by using the old version of this action: `xu-cheng/latex-action@1.1.0`.

> What would help the build time even more, is if installed packages could be committed to the docker container and cached (cache policy), but I still need to try if this actually works.

GitHub Action cache wouldn't work due to: (a) It won't work inside the docker container. (b) The additional installed packages are not in the single places. They are mixed with preinstalled packages from the docker image.

**Comment by PHPirates** [comment]
True, but I was hoping that installed packages could be cached so that then the build time would be faster.

I guess I need to learn to feel less bad about downloading 3GB of TeX Live every time ;) 

> GitHub Action cache wouldn't work due to: (a) It won't work inside the docker container. (b) The additional installed packages are not in the single place. They are mixed with preinstalled packages from the docker image.

Ah, so you can't cache a docker container? That would be unfortunate indeed. But from the docs it looks like you can cache files outside of the repo root, so that gives hope that I can cache packages when installing TeX Live in a different way. I really want a caching mechanism, hoping for build times under a minute as with Travis. Anyway, thanks for the help!
