### ISSUE TITLE
pre_compile broken with texlive 2024?

### ISSUE THREAD

**Issue by dpo** [xu-cheng/latex-action#155]
My workflows that use `pre_compile` started failing recently. After digging, I realized that they work again if I specify `texlive_version: 2023`. Did texlive 2024 break something?

**Comment by xu-cheng** [comment]
Please include a [minimal working example](https://tex.meta.stackexchange.com/questions/228/ive-just-been-asked-to-write-a-minimal-working-example-mwe-what-is-that) to demonstrate your problem.

**Comment by dpo** [comment]
Sorry for not providing a working example. I've been observing failures and I'm having trouble determining what causes them. Here is what happens: https://github.com/dpo/report/actions/runs/11061231024/job/30733418243?pr=18#step:3:90

This failure occurs in a PR that does not even modify any source `.tex` file. But it does occur in other repos of mine in PRs that do modify the `.tex` files. Initially, I thought something broke when texlive 2024 was introduced, but I may be wrong.

Here is my workflow file: https://github.com/dpo/report/blob/main/.github/workflows/build-latex-diff.yml#L17

Thank you in advance for any help.

**Comment by xu-cheng** [comment]
Looks to me there is no thing wrong in this action. You have to debug your bash command by yourself on why the passed bash code failed.

**Comment by xu-cheng** [comment]
You should try to run the bash command locally in a clean environment and check the bash exit code. If you are sure that the same setup used to work, it may because one of the TeXLive package is recently updated. This action by default always uses the latest TeXLive environment (updated monthly). You can try to reproduce it locally via the docker image used by this action <https://github.com/xu-cheng/latex-docker>. If it is the case, I would suggest you try to fix the underlying issue including asking help from the corresponding package authors. A possible short-term workaround is to use an old version of TeXLive, of which this action supports.

**Comment by dpo** [comment]
Thank you. Unforunately, I have this issue: https://github.com/xu-cheng/latex-docker/issues/18

**Comment by xu-cheng** [comment]
FYI, you can run amd64 docker image if you are using Mac with ARM cpu via `docker run --platform=linux/amd64 ...`
