### ISSUE TITLE
Output is different when using latex-action

### ISSUE THREAD

**Issue by daviddavo** [xu-cheng/latex-action#156]
I have created a document using a modified Awesome-CV template, and it works fine both on Overleaf and my Arch Linux machine with textlive, but when I use this action it shows some text on top of another.

I tried going over the action's log and running each command manually on my machine, and it works flawlessly. What could be happening? What else can I try?

**Comment by xu-cheng** [comment]
Please include a [minimal working example](https://tex.meta.stackexchange.com/questions/228/ive-just-been-asked-to-write-a-minimal-working-example-mwe-what-is-that) to demonstrate your problem.

**Comment by Auroric** [comment]
@daviddavo Did you ever find a solution to this? I'm running into the same issue.

**Comment by daviddavo** [comment]
Nup, I did not have time to do a minimal working example. I'm just downloading it from Overleaf, but the CV built for my website is still messed up. 

I see that you fixed by just using texlive 2022

https://github.com/Auroric/resume/commit/a51a44d0d72aebc94b84f26e05906a7f730250cc

**Comment by Auroric** [comment]
I actually thought you fixed it by changing the action to the more generic
one, and spent an hour being confused why it wasn’t working for me 😂

But yes, manually setting to texlive 2022 was the solution for my case. Not
sure why, since changing Overleaf to 2024 doesn’t introduce the spacing
error, but it works for now.

**Comment by xu-cheng** [comment]
The latest texlive image (i.e., 2024 for now) is updated monthly. So the problems you faced are likely due to some recent upstream package updates. It’s recommended to find source of the problem and report the bug to the corresponding package authors.

That being said, the issues are not related to this action. Please consider to only file issues here after you confirmed it is due to this action with minimum working examples in the future.
