### ISSUE TITLE
Is there anyway to tell the compiler not to use LaTex3?

### ISSUE THREAD

**Issue by whatgit** [xu-cheng/latex-action#31]
With the recent update, the code that used to be able to compile is no longer working. I am not sure what is the exact problem, but I guess it is because it compiles according to LaTeX3 now. 

```
./documents.cls:125: Package acro Error: The command \ProvideAcroEnding  is
 deprecated. Use
(acro)                \DeclareAcroEnding instead.

Type <return> to continue.
 ...                                              
                                                  
l.125 \ProvideAcroEnding
                         {possessive} {'s} {'s}

./documents.cls:132: LaTeX3 Error: Unknown argument type '\acro_possessive:
 ' for the command
(LaTeX3)        '\baseacg'.

For immediate help type H <return>.
```

Following the suggested changes, I was able to make it compile, but it won't compile on my local machine anymore.

p.s. I am using:
* Windows10 
* MiKTeX-pdfTeX 2.9.7338 (1.40.21) (MiKTeX 2.9.7400 64-bit)
* TeXstudio 2.12.22

I also try to compile it on Overleaf but that won't work either

**Comment by xu-cheng** [comment]
You problem has nothing to do with latex3. It seems that your template is using a command which is deprecated in the latest TeXLive 2020. 

Reading the document http://ctan.math.ca/tex-archive/macros/latex/contrib/acro/acro-manual.pdf, you may be able to \usepackage[version=2]{acro} to fallback to old behavior. 

If you have further problem, please show a proper minimal working example https://tex.meta.stackexchange.com/questions/3300/minimum-working-example-mwe

I would also suggest to you to ask for the package authors or https://tex.stackexchange.com/ since this is actually an issue of the package you are using instead of this action.

**Comment by xu-cheng** [comment]
FYI, this action updates TeXLive every month. Since your local Miktex and overleaf are still using the old version of TeXLive, you are seeing the current discrepancy.

**Comment by whatgit** [comment]
Thank you for your quick response.
