### ISSUE TITLE
Moderncv social symbols look different through this action

### ISSUE THREAD

**Issue by paddyroddy** [xu-cheng/latex-action#50]
I have a CI set up which builds my CV and then pushes to Dropbox. But I've realised that the social symbols look different via this action.  When I compile locally I do `latexmk -pdf CV.tex`. The CV is based on the `moderncv` package so appreciate it may not be directly relevant. But I cannot work out what is different. I've checked the `docker` image and `moderncv` is installed. Is this a font issue? Thanks for your help.

Locally (what I want):
![image](https://user-images.githubusercontent.com/15052188/109962911-b0c43080-7ce3-11eb-9ece-aceda95e0d92.png)

Done through the action (what I don't want):
![image](https://user-images.githubusercontent.com/15052188/109962936-b9b50200-7ce3-11eb-9a41-c7bbd8a0430f.png)

```
\documentclass[10pt,a4paper,sans]{moderncv}

\moderncvstyle{banking}
\moderncvcolor{green}

\usepackage[utf8]{inputenc}
\usepackage[scale=0.85]{geometry}

\name{Patrick}{Roddy}
\title{Curriculum Vit\ae}

\social[github]{paddyroddy}

\begin{document}
	\makecvtitle{}
\end{document}
```

**Comment by xu-cheng** [comment]
Are you sure that you are using pdflatex locally? I got the first symbol using lualatex and second symbol using pdflatex. If you want to use lualatex in this GitHub action, add `latexmk_use_lualatex: true` in the action input.

**Comment by paddyroddy** [comment]
Yep definitely as I said I compile locally using `latexmk -pdf`. I'm using a mac and would have installed latex using `brew install --cask mactex-no-gui`.

The top is what happens if I try your suggestion of using `lualatex`. The bottom is my local copy. There are more symbols besides github and the twitter one escapes the underscore i.e. `firstname\_surname` but locally this is `firstname_surname`
![image](https://user-images.githubusercontent.com/15052188/110136215-556b6e80-7dc7-11eb-878b-9c2ed4d48840.png)

**Comment by xu-cheng** [comment]
I suggest that you use pdflatex directly instead of latexmk to ensure the right latex engine is used. Maybe also try to remove temporary files first. 

Given the different appearance due to different latex engines, as tested locally, I think the issue you are facing comes from the morderncv package rather than this action. Maybe report this issue to there then. 

I don't see there is any actual issue related to this GitHub action, which simply runs latexmk inside [a latex docker](https://github.com/xu-cheng/latex-docker).

**Comment by paddyroddy** [comment]
So I just tried your other extension https://github.com/xu-cheng/texlive-action and run `pdflatex` directly and came up with same symbols. You may be right, I wonder whether there is a package I have installed which isn't in the `docker` but I'll close this for now

**Comment by paddyroddy** [comment]
Just tried running the following `Dockerfile` locally

```
FROM xucheng/texlive-full

ADD CV.tex .

RUN latexmk -pdf CV.tex
```

and then opened the PDF, and it looked as expected, so I have no idea what has caused this.

**Comment by xu-cheng** [comment]
The `xucheng/texlive-full` is outdated. The docker image (`ghcr.io/xu-cheng/texlive-full:latest`) used by this action is updated every month. 

Since you find desired result using old docker image, I strongly suspect the issue comes from updates in the texlive (be either moderncv or one of its dependencies). For example, you can try to update your local installed texlive (`sudo tlmgr update --self && sudo tlmgr update --all`) then test again.  Nevertheless, I suggest you to report your issue to moderncv.

**Comment by paddyroddy** [comment]
thank you, I've now run this locally and can replicate the original issue
