### ISSUE TITLE
The font "FontAwesome" cannot be found

### ISSUE THREAD

**Issue by litun5315** [xu-cheng/latex-action#67]
Hi, xu,

Sorry for disturbing you. 

I reused your fantastic ```latex-action``` tool in my [repo](https://github.com/HFUTTUG/HFUT_Resume), however, It did not support the "FontAwesome" font. But it works on the overleaf platform.

Is there any improvement? Or, did I incorrectly reuse the proposed tool?

Here is my building [log](https://github.com/litun5315/HFUT_Resume/runs/3277261479?check_suite_focus=true).

Best wishes.

**Comment by xu-cheng** [comment]
The problem seems come from the upstream package rather due to this GitHub action. You may refer to the following stackexchange questions to solve your problem:
* https://tex.stackexchange.com/questions/132888/fontawesome-font-not-found
* https://tex.stackexchange.com/questions/369068/how-can-i-use-the-fontawesome-package-with-xelatex
