### ISSUE TITLE
Need help on using `graphviz` package with this action

### ISSUE THREAD

**Issue by Jeff-Tian** [xu-cheng/latex-action#7]
Hi, details is here: #6 

I need help on this PR. I use PR instead of issue to take the advantage of the `code diff` feature there.

**Comment by xu-cheng** [comment]
I tweak your PR a bit in https://github.com/xu-cheng/latex-action/commit/fedf3b4873786d516c92d8c707034a09a0b2995e.

I will investigate what's going wrong.

**Comment by xu-cheng** [comment]
FYI, I can reproduce the same problem locally.

**Comment by xu-cheng** [comment]
I can confirm this issue has nothing to do with the action. It seems that `graphviz` package does not work well with `latexmk`. 

You can reproduce the same problem locally by running `latexmk -shell-escape -xelatex <root_file>`.

Currently, I have no solution. Though, you may find possible solution in the latexmk document.

**Comment by Jeff-Tian** [comment]
Thank you for your time, I'm not sure whether it's related to the setup on linux.

The expected pdf was created locally on my windows with TexLive 2019 installed.

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by xu-cheng** [comment]
You should reproduce the same issue using latexmk. Remember to remove auxiliary files first.

**Comment by xu-cheng** [comment]
@Jeff-Tian 

Since the problem is caused by the incompatibility between graphviz and latexmk.

You could use a different automation tools. For example, you can use arara as shown in the below:

* https://github.com/xu-cheng/latex-action/blob/ade9559d1998f6a51766a0d5d17161523a4c347d/.github/workflows/test.yml#L36-L46
* https://github.com/xu-cheng/latex-action/blob/ade9559d1998f6a51766a0d5d17161523a4c347d/test/graphviz.tex

**Comment by xu-cheng** [comment]
Also FYI, you can find more information on arara here: https://ctan.org/pkg/arara

**Comment by Jeff-Tian** [comment]
@xu-cheng Can't believe that, and you SAVED my life. Thanks a ton!
