### ISSUE TITLE
[Feature Request] Support for custom font

### ISSUE THREAD

**Issue by kazutoiris** [xu-cheng/latex-action#74]
Sometimes I may compile TeX which using custom font like FZShuSong and other Chinese font.

If it's possible to add `custom_font_dir` feature to GitHub Action and install font automatically.

Also thanks for your great action @xu-cheng.

**Comment by xu-cheng** [comment]
Unfortunately, there is no universal way to install font. The way to install custom fonts depend on your font type (tfm, type1, otf, etc.) as well as the LaTeX engine you are using (pdflatex, XeLaTeX, lualatex). 

I suggest you to add your custom font installation logic in `pre_compile`.

**Comment by kazutoiris** [comment]
If you can install font on Linux successfully, you can install font on Docker as the same way.

So there's universal way to install font
1. sudo apt install fontconfig ttf-mscorefonts-installer -y
2. cp font/* /usr/share/fonts/truetype
3. mkfontscale && mkfontdir && fc-cache -fv

I've tested on GitHub Action with `ubuntu-latest` image. So it's may possible to install font on Docker image.

I'm glad to make a PR to add this feature.

**Comment by ceciliachan1979** [comment]
For a causal Latex user like me, trying to get some Chinese character to show up is getting really frustrating.

Here is a list of things I tried and none works, I listed these out so that other don't need to try.

Attempt 1:
```
\documentclass{article}
\usepackage[UTF8]{ctexart}
```

Result:
```
! LaTeX Error: File `ctexart.sty' not found.
```

Attempt 2
```
%!TEX program = xelatex
\documentclass{article}
\usepackage[UTF8]{ctex}
```

Result:
```
! LaTeX Error: File `ctexart.sty' not found.
```

Attempt 3:
```
\documentclass{article}
\usepackage[UTF8]{ctex}
```

Result:
```
Critical Package ctex Error: CTeX fontset `fandol' is unavailable in current
```

Attempt 4
```
%!TEX program = xelatex
\documentclass{article}
\usepackage[UTF8]{ctex}
```

Result:
```
Critical Package ctex Error: CTeX fontset `fandol' is unavailable in current
```

Attempt 5
```
%!TEX program = xelatex
\documentclass{article}
\usepackage[UTF8]{xeCJK}
```

Result:
```
Critical Package xeCJK Error: The xeCJK package requires XeTeX to function.
```

> That makes me wonder the %!TEX thing is just not working.


Attempt 6
```
% arara: xelatex: { shell: yes, interaction: nonstopmode }
\documentclass{article}
\usepackage[UTF8]{xeCJK}
```

Result:
```
Critical Package xeCJK Error: The xeCJK package requires XeTeX to function.
```

I am running out of tricks.

@kazutoiris, did you get Chinese to work?

**Comment by xu-cheng** [comment]
@ceciliachan1979 `%!TEX` is not recognized by this action. You need to manually set the latex engine in the action input. See https://github.com/xu-cheng/latex-action#how-to-use-xelatex-or-lualatex-instead-of-pdflatex

For fonts, only default fonts from texlive is pre installed. You can use `extra_fonts` action input to install additional otf/ttf fonts. 

Please open a new issue instead of commenting on the old one in the future.
