### ISSUE TITLE
Build multiple tex files which are relying on header.tex one folder above

### ISSUE THREAD

**Issue by florian30491** [xu-cheng/latex-action#79]
Hi @xu-cheng 

i have a problem with using your action.

I want to build multiple excerise sheets, which are all relying on the same strucutre (header.tex) which is located one folder above the exercise sheets.

This is unfortunatly not wokring. When i build the tex files locally it is working.

I have prepared here a minimal working example: https://github.com/florian30491/LatexBuildIssue

Could you tell me maybe what i am doing here wrong?

Thank you very much.

Greetings,
Florian

**Comment by xu-cheng** [comment]
I think your issue comes from the fact latex doesn’t support relative path to the source file. In latex, the path is always relatively to the current working directory, which is the root of your git repo in your case.  Therefore, you probably need to tweak your input file path or working directory or both. 

Noted that since your use case is relatively more complex, a good solution is to write a Makefile to compile all your documents, which can also help local development. To build latex documents in GitHub Action using Makefile, I suggest you to use https://github.com/xu-cheng/texlive-action instead.

**Comment by alessandro-massarenti** [comment]
@florian30491 May I ask how you resolved your issue?

I've got a repo with multiple documents each with their own local files.
On my own computer the compiler understands that and makes the path local to each main document file but on the actions the path is global to the repository.

How should I approach this difference in compilation? how can i compile the same way on the action and on my own machine? What do you recommend? let me know if a link to my repo can be useful. Thanks in advance.

**Comment by alessandro-massarenti** [comment]
> @florian30491 May I ask how you resolved your issue?
> 
> I've got a repo with multiple documents each with their own local files. On my own computer the compiler understands that and makes the path local to each main document file but on the actions the path is global to the repository.
> 
> How should I approach this difference in compilation? how can i compile the same way on the action and on my own machine? What do you recommend? let me know if a link to my repo can be useful. Thanks in advance.

Just for the sake of historicization:
Finally, after lot's of search i found that you can set the _working dir_ path for every job with:

```
working_directory: _path_
work_in_root_file_dir: true 
```

**This solved my problem**, i can now compile multiple pdf each with it's own structure.
