### ISSUE TITLE
Possible to use older compiler version?

### ISSUE THREAD

**Issue by emgns04** [xu-cheng/latex-action#99]
Hello I have encountered an issue with one of my documents which no longer renders correctly on 2022 LaTeX. Can we provide an older compiler version and if so could you show some example of how this would look in the action?

**Comment by xu-cheng** [comment]
Due to the restrictions of GitHub actions, you would have to fork this action and change [the docket base image](https://github.com/xu-cheng/latex-action/blob/1b51dd6505fec648151c2e7775e6b4ba274c8ee3/Dockerfile#L1) to [an old version](https://github.com/xu-cheng/latex-docker/pkgs/container/texlive-full/versions).

However, I would strongly suggest you to either fix your latex code or report your issue to the corresponding latex packages. Latex eco system as a whole usually only provides support to the latest version of latex environments.
